<?xml version = "1.0" ?><!-- Generated by Zhaohui Xing TDRBuilder v1.0 --><xpl version = "1.0">
<module name = "test2" date = "Fri Mar 25 19:02:39 2005
">
<entry>
<input>
<variable type = "float" name = "f" default_value = "0.00000000000000000000000000000000"/>
<variable type = "float" name = "g" default_value = "0.00000000000000000000000000000000"/>
</input></entry><initialize>
<next id = "0"/>
<global/>
<local/>
</initialize><processor name = "Processor" id = "0" type = "3">
<previous id = "-3"/>
<next id = "-4"/>
<method>
<![CDATA[
long Processor(void)
{
	g =  12456666632.3456782134521478945677;
	f = 4.785;
	m_nRegister = -4;
	return m_nRegister;
}]]>
</method>

</processor></module></xpl><!-- Powered by Zhaohui Xing TDRBuilder v1.0 -->