#ifndef __XVSB_FILCONST_H__
#define __XVSB_FILCONST_H__

#define XVSM_MACRO_HEXT				L".h"
#define XVSM_MACRO_CPPEXT			L".cpp"
#define XVSM_MACRO_TXTEXT			L".txt"
#define XVSM_MACRO_IFNOTDEF			L"#ifndef"
#define XVSM_MACRO_DEFINE			L"#define"
#define XVSM_MACRO_ENDIF			L"#endif"
#define XVSM_PREV_DUNDERSCORE		L"  __"
#define XVSM_LAST_DUNDERSCORE		L"__"
#define XVSM_SUNDERSCORE			L"_"
#define XVSM_MACRO_UPPERH			L"H"
#define XVSM_MACRO_CLASSID			L"class"
#define XVSM_MACRO_LB				L"{"
#define XVSM_MACRO_RB				L"}"
#define XVSM_MACRO_SEMICOLON		L";"
#define XVSM_MACRO_INCLUDE			L"#include"
#define XVSM_MACRO_INCXMATH			L"#include \"xvsmath.h\""
#define XVSM_MACRO_INCMATHH			L"#include <math.h>"
#define XVSM_MACRO_DCOLON			L"::"
#define XVSM_MACRO_COLON			L":"
#define XVSM_MACRO_VOIDPARA			L"(void)"
#define XVSM_MACRO_PREVOID			L"void"
#define XVSM_MACRO_PRELONG			L"long"
#define XVSM_MACRO_NOTSIGN			L"~"
#define XVSM_MACRO_PUBLIC			L"public"
#define XVSM_MACRO_PROTECTED		L"protected"
#define XVSM_MACRO_PRIVATE			L"private"

#define XVSM_MACRO_VOIDFNSIGN		L"()"
#define XVSM_MACRO_INTTYPE			L"int"
#define XVSM_MACRO_MINUSONE			L"-1"
#define XVSM_MACRO_ASSIGN			L"="
#define XVSM_MACRO_COUNTERVAR		L"m_nRegister"
#define XVSM_MACRO_RETURNCUNTER		L"\treturn m_nRegister;"
#define XVSM_MACRO_SETCOUNTER		L"m_nRegister = "
#define XVSM_MACRO_SWITCHCOUNTER	L"switch(m_nRegister)"

#define XVSM_MACRO_SETENTRY			L"Startup"
#define XVSM_MACRO_INITIALIZE		L"Initialize"
#define XVSM_MACRO_RUNFUNC			L"Run"
#define XVSM_MACRO_RUNSTEPFUNC		L"StepProcess"
#define XVSM_MACRO_RUNDO			L"do"
#define XVSM_MACRO_RUNWHILE			L"while(m_nRegister != -4 && m_nRegister != -1)"

#define XVSM_XML_CDATALEFT			L"<![CDATA["
#define XVSM_XML_CDATARIGHT			L"]]>"

#define XVSM_XML_COMMENTLEFT		L"<!-- "
#define XVSM_XML_COMMENTRIGHT		L" -->"

#define XVSM_TAG_XPL				L"xpl"
#define XVSM_TAG_XVS				L"xvs"
#define XVSM_TAG_MODULE				L"module"

#define XVSM_TAG_ENTRY				L"entry"
#define XVSM_TAG_INITIALIZE			L"initialize"
#define XVSM_TAG_PROCESSOR			L"processor"
#define XVSM_TAG_EXIT				L"exit"

#define XVSM_TAG_INPUT				L"input"
#define XVSM_TAG_GLOBAL				L"global"
#define XVSM_TAG_LOCAL				L"local"

#define XVSM_TAG_LINK				L"link"

#define XVSM_TAG_VARIABLE			L"variable"
#define XVSM_TAG_ARRAY				L"array"
#define XVSM_TAG_ARRAYELEMENT		L"arrayelement"

#define XVSM_TAG_COME				L"previous"
#define XVSM_TAG_GO					L"next"

#define XVSM_TAG_YESGO				L"next_if_true"
#define XVSM_TAG_NOTGO				L"next_if_false"

#define XVSM_TAG_METHOD				L"method"

////
#define XVSM_TAG_DIMENSION			L"dimension"
#define XVSM_TAG_POINTS				L"points"
#define XVSM_TAG_POINT				L"point"

#define XVSM_TAG_CENTER				L"center"
#define XVSM_TAG_SIZE				L"size"

#define XVSM_TAG_LPUNODE		    L"logicaltitle"

#define XVSM_TAG_HEADLINK			L"headlink"
#define XVSM_TAG_TAILLINK			L"taillink"

#define XVSM_TAG_EQUATION			L"equation"
#define XVSM_TAG_COMPARE			L"comparison"

#define XVSM_ATTR_VER				L"version"
#define XVSM_ATTR_NAME				L"name"
#define XVSM_ATTR_DATE				L"date"

#define XVSM_ATTR_TYPE				L"type"
#define XVSM_ATTR_DEFVALUE			L"default_value"
#define XVSM_ATTR_ARRAYTYPE			L"element_type"
#define XVSM_ATTR_ARRAYSIZE			L"array_size"
#define XVSM_ATTR_INDEX				L"index"
#define XVSM_ATTR_ID				L"id"
#define XVSM_ATTR_INITVALUE			L"initial_value"
#define XVSM_ATTR_FINALVALUE		L"final_value"

#define XVSM_ATTR_X					L"x"
#define XVSM_ATTR_Y					L"y"

#define XVSM_ATTR_YES				L"true"
#define XVSM_ATTR_NO				L"false"

#define XVSM_ATTR_LEFT				L"left"
#define XVSM_ATTR_RIGHT				L"right"
#define XVSM_ATTR_CMP				L"compare"
#define XVSM_ATTR_LGLINK			L"relation"

#define XVSM_MACRO_CURVER			L"1.0"

#define XVSM_MACRO_INPUTVAR			L"Input Variables"
#define XVSM_MACRO_GLOBALVAR		L"Global Variables"
#define XVSM_MACRO_LOCALVAR			L"Local Variables"
#define XVSM_MACRO_ENDVAR			L"End"

#define XVSM_MACRO_NAME				L"Name"
#define XVSM_MACRO_TYPE				L"Type"
#define XVSM_MACRO_DEFVALUE			L"Initial Value"
#define XVSM_MACRO_REVALUE			L"Final Value"
#define XVSM_MACRO_ARRAYTYPE		L"Array Element Type"
#define XVSM_MACRO_ARRAY			L"Array"
#define XVSM_MACRO_ARRAYSIZE		L"Array Size"
#define XVSM_MACRO_MODULE			L"Module"
#define XVSM_MACRO_MODULEEND		L"End of Module"
#define XVSM_MACRO_TIME				L"Time"

#define XVSM_MACRO_HEADER			L"Generated by Zhaohui Xing TDRBuilder v1.0"
#define XVSM_MACRO_FOOTER			L"Powered by Zhaohui Xing TDRBuilder v1.0"

#endif
