/*Generated by Zhaohui Xing TDRBuilder v1.0*/
#ifndef  __CLOOPTEST_H__
#define  __CLOOPTEST_H__


class CLoopTest
{
public:
	CLoopTest(void);
	~CLoopTest(void);
private:
	long m_nRegister;

public:
	void Startup(void);


public:
	double di1;
public:
	long Initialize(void);


public:
	bool gb1;
	double gf1;


protected:
	int i;


public:
	void Run(void);
	long StepProcess(void);


private:
	long Loop_Process(void);
	long Loop_Condition(void);
	long Final_Process(void);
	long Initial_Assignment(void);
};


#endif
/*Powered by Zhaohui Xing TDRBuilder v1.0*/
