//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VxBuilder.rc
//
#define IDR_VxBuilderTYPE_SRVR_IP       4
#define IDR_VxBuilderTYPE_SRVR_EMB      5
#define IDR_MODULE_SRVR_IP              6
#define IDR_MODULE_SRVR_EMB             7
#define IDR_CLASS_SRVR_IP               8
#define IDR_CLASS_SRVR_EMB              9
#define IDM_FILE_NEWMODULE              10
#define IDM_FILE_NEWCLASS               11
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDR_MAINFRAME                   128
#define IDR_VxBuilderTYPE               129
#define IDR_VXMODULE                    130
#define IDR_VXCLASS                     131
#define IDD_PUTOOL                      132
#define IDI_PPU                         133
#define IDI_LOGIC                       134
#define IDI_LINK                        135
#define IDI_ARROW                       136
#define IDR_MENUBMP                     137
#define IDR_ARROW1                      138
#define IDR_ARROW2                      139
#define IDR_ARROW3                      140
#define IDR_ARROW4                      141
#define IDR_ARROW5                      142
#define IDR_ARROW6                      143
#define IDR_ARROW7                      144
#define IDR_ARROW8                      145
#define IDC_HAND2                       146
#define IDC_DRAGPU                      147
#define IDC_DRAGLU                      148
#define IDC_DRAGLK                      149
#define IDC_NODROP                      150
#define IDI_CLSBLK                      151
#define IDD_PUTOOLPANEL                 152
#define IDI_SMD                         153
#define IDI_LINK2                       154
#define IDI_DOCICO                      155
#define IDC_CLSCUR                      156
#define IDC_DOCCUR                      157
#define IDD_OUTPUT                      158
#define IDD_VARPANEL                    159
#define IDD_VARLISTPANEL                160
#define IDD_OUTPUTPANEL                 161
#define IDD_DLGPARAM                    162
#define IDD_DLGDTYPESEL                 163
#define IDD_DLGVARIABLE                 164
#define IDD_DLGLOCALVARS                165
#define IDD_DLGEDITLG                   166
#define IDD_DLGEDITPU                   167
#define IDD_DLGEQEDIT2                  168
#define IDD_DLGCPUMAP                   169
#define IDD_DLGPARAMAP                  170
#define IDR_VXCLSFN                     171
#define IDD_DLGINPUTNS                  172
#define IDD_DLGCLSEDIT                  173
#define IDD_DLGCLSFNEDIT                174
#define IDD_DLGINPUTCLS                 175
#define IDD_CLSUSEPAGE                  176
#define IDD_CLSDATAPAGE                 177
#define IDD_CLSFNPAGE                   178
#define IDB_ICOBMP1                     179
#define IDR_ARROW9                      180
#define IDR_ARROW10                     181
#define IDD_DLGDATATYPE                 182
#define IDD_DLGFNPROTOTYPE              183
#define IDD_DLGPARATYPESEL				184
#define IDC_BTNPPU                      1000
#define IDC_BTNSMD                      1001
#define IDC_BTNLPU                      1002
#define IDC_BTNLINK                     1003
#define IDC_BTNCLS                      1004
#define IDC_BTNCLSLINK                  1005
#define IDC_BTNDOC                      1006
#define IDC_BTNCLSDOC                   1007
#define IDC_LISTOUTPUT                  1008
#define IDC_VARLIST                     1009
#define IDC_LISTINPUT                   1010
#define IDC_BTNADD                      1011
#define IDC_BTNEDIT                     1012
#define IDC_BTNDEL                      1013
#define IDC_LISTBOTH                    1014
#define IDC_BTNADD4                     1014
#define IDC_BTNADD2                     1015
#define IDC_BTNEDIT2                    1016
#define IDC_BTNDEL2                     1017
#define IDC_LISTOUTPUT2                 1018
#define IDC_BTNDATA                     1019
#define IDC_BTNCLASS                    1020
#define IDC_BTNADD3                     1021
#define IDC_BTNEDIT3                    1022
#define IDC_BTNDEL3                     1023
#define IDC_TEXTNAME                    1024
#define IDC_EDITNAME                    1025
#define IDC_TEXTTYPE                    1026
#define IDC_EDITNAME2                   1026
#define IDC_CMBTYPE                     1027
#define IDC_TEXTARYTYPE                 1027
#define IDC_STATICVDV                   1028
#define IDC_EDITVALUE                   1029
#define IDC_ARRAYSIZE                   1030
#define IDC_EDITARYSIZE                 1031
#define IDC_ARRAYTYPE                   1032
#define IDC_CMBAETYPE                   1033
#define IDC_ARRAYDEFVALUE               1034
#define IDC_LISTAEVAL                   1035
#define IDC_UPDATE                      1036
#define IDC_SETVALUE                    1037
#define IDC_BTNCLEAN                    1038
#define IDC_STATICAET                   1039
#define IDC_LISTLOCAL                   1040
#define IDC_LISTLGCMP                   1041
#define IDD_DLGCMPEDIT2                 1042
#define IDC_EDITLSIDE                   1043
#define IDC_CMBPRECNDT                  1044
#define IDC_EDITRSIDE                   1045
#define IDC_CMBLGCMP                    1046
#define IDC_INPUTLIST                   1047
#define IDC_GLOBALLIST                  1048
#define IDC_LOCALLIST                   1049
#define IDC_BOOLLIST                    1050
#define IDC_BTNADDLEFT                  1051
#define IDC_BTNADDRIGHT                 1052
#define IDC_BTNHELP                     1053
#define IDC_OUTPUTLIST                  1054
#define IDC_LISTEQUAT                   1055
#define IDC_EDITLVAR                    1056
#define IDC_EDITEQ                      1057
#define IDC_OPERATORLIST                1058
#define IDC_BTNADDOPER                  1059
#define IDC_EDITPATH                    1060
#define IDC_BTNBROWSE                   1061
#define IDC_EDITTYPE                    1062
#define IDC_EDITVAR                     1063
#define IDC_BTNEDITCFN                  1064
#define IDC_CLSPAGECTRL                 1065
#define IDC_TREENS                      1066
#define IDC_TXTNAME                     1068
#define IDC_BTNSETPARENT                1069
#define IDC_BTNSETPARENT2               1070
#define IDC_BTNDELPARENT                1070
#define IDC_TREEDATA                    1070
#define IDC_BTNADDTYPE                  1072
#define IDC_TXTTYPE                     1073
#define IDC_TXTARYETYPE                 1074
#define IDC_CAPAEDVAL                   1075
#define IDC_DTYPEGRP                    1076
#define IDC_BTNADDTYPE2                 1077
#define ID_CANCEL_EDIT_SRVR             32769
#define IDC_TBARCOMB                    32770
#define IDM_VIEW_GRID                   32771
#define IDM_VIEW_SHADOW                 32772
#define IDM_ARROWMENU                   32773
#define IDM_ARROW1                      32774
#define IDM_ARROW2                      32775
#define IDM_ARROW3                      32776
#define IDM_ARROW4                      32777
#define IDM_ARROW5                      32778
#define IDM_ARROW6                      32779
#define IDM_ARROW7                      32780
#define IDM_ARROW8                      32781
#define IDM_EDIT_COPYALL                32782
#define IDM_EDIT_DELETE                 32783
#define IDM_EDIT_PROPERTY               32784
#define IDM_ADDSPU                      32785
#define IDM_ADDSMD                      32786
#define IDM_ADDLPU                      32787
#define IDM_ADDLINK                     32788
#define IDM_ADDCOMMENT                  32789
#define IDM_LINKERTAIL90                32790
#define ID_BUTTON32790                  32790
#define IDM_LINKERTAIL270               32791
#define IDM_LINKERTURN90                32792
#define IDM_LINKERTURN180               32793
#define IDM_LINKERTURN270               32794
#define IDM_ADDCLASS                    32795
#define IDM_VIEW_TOOLBOX                32796
#define IDM_VIEW_VARIABLE               32797
#define IDM_VIEW_OUTPUT                 32798
#define IDM_VIEW_TOOLTIPS               32799
#define IDM_MODULE_COMPILE              32800
#define IDM_MODULE_RUN                  32801
#define IDM_MODULE_PAUSE                32802
#define IDM_MODULE_RESUME               32803
#define IDM_MODULE_STOP                 32804
#define IDM_MODULE_ANALYSE              32805
#define IDM_EXPORTTEXTRESULT            32806
#define IDM_EXPORTXMLRESULT             32807
#define IDM_EXPORTEXCELESULT            32808
#define IDM_EXPORTWORDRESULT            32809
#define IDM_ARROW9                      32810
#define IDM_ARROW10                     32811
#define IDS_PUPANELTITLE                40001
#define IDS_PROPERTYMENU                40002
#define IDS_VARPANELTITLE               40003
#define IDS_OUTPUTPAENLTITLE            40004
#define IDS_VARNAMEEMPTY                40005
#define IDS_VARNAMESAME                 40006
#define IDS_NOVARTYPESEL                40007
#define IDS_INVALIDINPUT                40008
#define IDS_BYTEOUTRANGE                40009
#define IDS_INVALIDBOOL                 40010
#define IDS_DELETINPUTVAR               40011
#define IDS_NOTARRAYTYPE                40012
#define IDS_ARRAYCHANGE                 40013
#define IDS_ARRAYSIZEINVALID            40014
#define IDS_AETYPEINVALID               40015
#define IDS_NOAESELECTED                40016
#define IDS_DELETEBOTHVAR               40017
#define IDS_DELETEOUTPUTVAR             40018
#define IDS_DELETELOCALVAR              40019
#define IDS_INVALIDPUIDANDMAN           40020
#define IDS_DELETEINPUTVAR              40021
#define IDS_VARIABLETITLE               40022
#define IDS_TYPEELEMENTTITLE            40023
#define IDS_OPERATORTITLE               40024
#define IDS_EXAMPLETITLE                40025
#define IDS_BOOLEANCONST                40026
#define IDS_BOOLEANTRUE                 40027
#define IDS_BOOLEANFALSE                40028
#define IDS_DELETECMP                   40029
#define IDS_CMPLEFTINVALID              40030
#define IDS_CMPRIGHTINVALID             40031
#define IDS_CMPSIGNINVALID              40032
#define IDS_CMPLGRINVALID               40033
#define IDS_EXPYNTAXERROR               40034
#define IDS_EMPTYEXP                    40035
#define IDS_DELETEEQ                    40036
#define IDS_ARRAYVARLISTFMT             40037
#define IDS_EQLEFTINVALID               40038
#define IDS_EMPTYPATH                   40039
#define IDS_EMPTYNAME                   40040
#define IDS_XVSMATHINVALID              40041
#define IDS_FAILCREATEFILE              40042
#define IDS_FAILFINDRES                 40043
#define IDS_FAILLOADRES                 40044
#define IDS_FAILLOCKRES                 40045
#define IDS_FAILOPENFILE                40046
#define IDS_NOVALIDVAR                  40047
#define IDS_NOVALIDNS                   40048
#define IDS_NOVALIDCLSNAME              40049
#define IDS_NOVALIDCNAMEERR             40050
#define IDS_CLSNAMEUSED                 40051
#define IDS_SAMENSEDITING               40052
#define IDS_BUILDINTYPE                 40053
#define IDS_ARRAYTYPE                   40054
#define IDS_AEDTNOTARY                  40055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
